### ISSUE TITLE
Peer code review

### ISSUE THREAD

**Issue by chimwemwe007** [chelmerrox/my-portfolio#3]
- Good semantics on your html
- Followed appropriate css semants
- Good following of git flow.

**Comment by chelmerrox** [comment]
Thanks for the review! 🙂

**Comment by elhamatokhi** [comment]
Hello, my bestieNo problem. Sent from Mail for Windows From: LosaliniSent: Thursday, 2 June, 2022 1:25 AMTo: chelmerrox/my-portfolioCc: elhamatokhi; CommentSubject: Re: [chelmerrox/my-portfolio] Peer code review (Issue #3) Thanks for the review! 🙂—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
