### ISSUE TITLE
Morning Session - Suggestion and Question

### ISSUE THREAD

**Issue by gak92** [chelmerrox/my-portfolio#4]
Your code looks very nice and clean, but I have one question and one suggestion:

My Question:
1- Why did you use 'mobile' for the name of each class. Is there any good reason for that?
My Suggestion:
2- I would suggest to use one single class for the cards like you use "<div class="card-1-mobile">" and " <div class="card-2-mobile">".

Or if I miss anything that you used for any particular reason.
Thanks

**Comment by chelmerrox** [comment]
Thank you for your review! 🙂To answer your questions:

1. those classes are for the mobile version of the project. In the desktop version, those classes would be set to display: none so that it doesn't show in the desktop version
2. I had used specific class names for each card so that when I position them to where it starts & ends using grid, I can target the specific card.

I hope these answers your questions. 👍🏽
